// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ozon_Tech_Api.Contexts;

#nullable disable

namespace Ozon_Tech_Api.Migrations
{
    [DbContext(typeof(Contexts.Contexts.ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ozon_Tech_Api.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.File_Recommendations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("File_To_SendId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("File_To_SendId");

                    b.ToTable("File_Recommendations");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.File_To_Send", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("File_TopicsId")
                        .HasColumnType("integer");

                    b.Property<int>("Send_OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("File_TopicsId");

                    b.HasIndex("Send_OrderId");

                    b.ToTable("File_To_Send");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.File_Topics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("File_Topics");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("File_To_SendId")
                        .HasColumnType("integer");

                    b.Property<int>("Message_TextId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("File_To_SendId");

                    b.HasIndex("Message_TextId");

                    b.HasIndex("UserId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Message_Text", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Send_OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Send_OrderId");

                    b.ToTable("Message_Text");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Send_OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Send_OrderId");

                    b.ToTable("Reminder");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Send_Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Order_Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Send_Order");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Statuses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.User_Responses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("File")
                        .HasColumnType("text");

                    b.Property<string>("Text_Response")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("User_Responses");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Users_Course_End", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Users_Course_End");
                });

            modelBuilder.Entity("Ozon_Tech_Api.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date_Of_Birth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusesId")
                        .HasColumnType("integer");

                    b.Property<int>("Studet_Code")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StatusesId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Course", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.File_Recommendations", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Tables.File_To_Send", "File_To_Send")
                        .WithMany()
                        .HasForeignKey("File_To_SendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File_To_Send");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.File_To_Send", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Tables.File_Topics", "File_Topics")
                        .WithMany()
                        .HasForeignKey("File_TopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ozon_Tech_Api.Tables.Send_Order", "Send_Order")
                        .WithMany()
                        .HasForeignKey("Send_OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File_Topics");

                    b.Navigation("Send_Order");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Message", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Tables.File_To_Send", "File_To_Send")
                        .WithMany()
                        .HasForeignKey("File_To_SendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ozon_Tech_Api.Tables.Message_Text", "Message_Text")
                        .WithMany()
                        .HasForeignKey("Message_TextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ozon_Tech_Api.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File_To_Send");

                    b.Navigation("Message_Text");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Message_Text", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Tables.Send_Order", "Send_Order")
                        .WithMany()
                        .HasForeignKey("Send_OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Send_Order");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Reminder", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Tables.Send_Order", "Send_Order")
                        .WithMany()
                        .HasForeignKey("Send_OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Send_Order");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.User_Responses", b =>
                {
                    b.HasOne("Ozon_Tech_Api.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ozon_Tech_Api.Tables.Users_Course_End", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Tables.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ozon_Tech_Api.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ozon_Tech_Api.User", b =>
                {
                    b.HasOne("Ozon_Tech_Api.Tables.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ozon_Tech_Api.Tables.Statuses", "Statuses")
                        .WithMany()
                        .HasForeignKey("StatusesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
